
colors:
- darkgreen
- slateblue
- turquoise
- cornflowerblue
- orange
- teal
- purple
- magenta
- chocolate


# views: |
#   (map div (range 9)
#   border-width=10
#   corner-radius=75
#   border='black'
#   background=colors)


views:
- : $div
  background: (item colors 2)
  border: black
  border-width: 10
  corner-radius: 30
  capture:
    move: div1-mouse-pos
    down: div1-mouse-down


layout:
  type: $grid
  rows: [150px, 1, 150px]
  cols: [150px, 1, 150px]
